### ISSUE TITLE
运行roslaunch turtlebot3sim single_robot_origin.launch 时报错，缺少文件

### ISSUE THREAD

**Issue by bruz-z** [KunSong-L/FHT-Map#1]
您好，我运行roslaunch turtlebot3sim single_robot_origin.launch 时报错
**[ INFO] [1731569430.698439536]: I1114 15:30:30.000000 170794 map_builder_bridge.cc:136] Added trajectory with ID '0'.
Traceback (most recent call last):
  File "/home/dell/Desktop/lsq/fht_map_ws/src/FHT-Map/turtlebot3sim/script/map_padding.py", line 101, in <module>
    numbers = re.findall(r"\d+", sorted_file_paths[-1])
IndexError: list index out of range
[INFO] [1731569431.041748, 2.083000]: Publishing combined odometry on /ImuChange
[map_padding-7] process has died [pid 170816, exit code 1, cmd /home/dell/Desktop/lsq/fht_map_ws/src/FHT-Map/turtlebot3sim/script/map_padding.py __name:=map_padding __log:=/home/dell/.ros/log/4dd99942-a25a-11ef-ba85-6d7d6f44b244/map_padding-7.log].
log file: /home/dell/.ros/log/4dd99942-a25a-11ef-ba85-6d7d6f44b244/map_padding-7*.log**
后面我去看代码，发现map_padding.py里面需要地图相关文件
![2024-11-14 15-45-41屏幕截图](https://github.com/user-attachments/assets/10760f05-f2db-4e05-8dc1-14aaa3f65944)
能提供一下这些地图文件嘛

**Comment by KunSong-L** [comment]
Sorry for the problem. These lines are used for recording the experiment results. So, you can just remove all the lines that write data to your computer.

I also pushed a new version of _map_padding.py_. You can pull this repository again or just change that file.

If you get any problem, do not hesitate to contact me. I am glad to see my work receive your attention.

**Comment by bruz-z** [comment]
现在可以成功运行了，但还是会报一些warn和error，对结果有影响吗
**[ERROR] [1731588716.526715306, 438.624000000]: Global Frame: robot1/odom Plan Frame size 238: robot1/map

[ WARN] [1731588716.526770728, 438.624000000]: Could not transform the global plan to the frame of the controller
[ERROR] [1731588716.628119491, 438.723000000]: Extrapolation Error: Lookup would require extrapolation 0.007000000s into the future.  Requested time 438.700000000 but the latest data is at time 438.693000000, when looking up transform from frame [robot1/odom] to frame [robot1/map]

[ERROR] [1731588716.628208814, 438.723000000]: Global Frame: robot1/odom Plan Frame size 238: robot1/map

[ WARN] [1731588716.628252863, 438.723000000]: Could not transform the global plan to the frame of the controller
[ERROR] [1731588716.728310587, 438.823000000]: Extrapolation Error: Lookup would require extrapolation 0.007000000s into the future.  Requested time 438.800000000 but the latest data is at time 438.793000000, when looking up transform from frame [robot1/odom] to frame [robot1/map]

[ERROR] [1731588716.728394886, 438.823000000]: Global Frame: robot1/odom Plan Frame size 238: robot1/map

[ WARN] [1731588716.728439079, 438.823000000]: Could not transform the global plan to the frame of the controller
[ERROR] [1731588716.830395452, 438.923000000]: Extrapolation Error: Lookup would require extrapolation 0.007000000s into the future.  Requested time 438.900000000 but the latest data is at time 438.893000000, when looking up transform from frame [robot1/odom] to frame [robot1/map]

[ERROR] [1731588716.830483011, 438.923000000]: Global Frame: robot1/odom Plan Frame size 238: robot1/map

[ WARN] [1731588716.830535531, 438.923000000]: Could not transform the global plan to the frame of the controller
[ERROR] [1731588716.930862026, 439.023000000]: Extrapolation Error: Lookup would require extrapolation 0.007000000s into the future.  Requested time 439.000000000 but the latest data is at time 438.993000000, when looking up transform from frame [robot1/odom] to frame [robot1/map]

[ERROR] [1731588716.930945065, 439.023000000]: Global Frame: robot1/odom Plan Frame size 238: robot1/map

[ WARN] [1731588716.930995148, 439.023000000]: Could not transform the global plan to the frame of the controller
[ERROR] [1731588717.032822485, 439.123000000]: Extrapolation Error: Lookup would require extrapolation 0.008000000s into the future.  Requested time 439.100000000 but the latest data is at time 439.092000000, when looking up transform from frame [robot1/odom] to frame [robot1/map]

[ERROR] [1731588717.032917922, 439.123000000]: Global Frame: robot1/odom Plan Frame size 238: robot1/map

[ WARN] [1731588717.032957131, 439.123000000]: Could not transform the global plan to the frame of the controller
[ERROR] [1731588717.133235199, 439.223000000]: Extrapolation Error: Lookup would require extrapolation 0.008000000s into the future.  Requested time 439.200000000 but the latest data is at time 439.192000000, when looking up transform from frame [robot1/odom] to frame [robot1/map]

[ERROR] [1731588717.133330548, 439.223000000]: Global Frame: robot1/odom Plan Frame size 238: robot1/map**
运行结果如下
![2024-11-14 20-54-02屏幕截图](https://github.com/user-attachments/assets/6b0d04aa-e9c7-4836-9bfd-d165eb4f313a)

**Comment by KunSong-L** [comment]
this is a not a big problem, I do not meet this problem when I was running on my computer.
This problem seems to be related to the tf in ROS, and the SLAM module can lead to this problem.
You can check the related part if you want to solve it.

**Comment by bruz-z** [comment]
好的谢谢
