### ISSUE TITLE
请问论文里面的地图存储量是怎么计算的

### ISSUE THREAD

**Issue by bruz-z** [KunSong-L/FHT-Map#2]
![屏幕截图 2024-12-10 184504](https://github.com/user-attachments/assets/95cf48dd-7316-4e43-a419-f5933feead63)
如图，里面的storage是怎么计算的，我看代码里也没有相应内容，如果是查看rosbag的话文件大小是MB级别的

**Comment by KunSong-L** [comment]
这个我是手动计算的，你可以把每个节点内部储存内容的storage加起来。比如说主节点要储存一个512维度的向量，储存成float类型。以及其他的如位置、id等信息。这样就能算出来这个数了。
